Feat: Add PSO gov script
mento-protocol/mento-deployment pull request #209
Opened 2024-08-16 15:03 UTC by denviljclarke

### Description

_A few sentences describing the overall effects and goals of the pull request's commits.
What is the current behavior, and what is the updated/expected behavior with this PR?_

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2024-08-20 12:21 UTC, philbow61 commented on script/upgrades/PUSO/Config.sol
> +    rateFeedConfig.rateFeedID = Config.rateFeedID("PHPUSD");
```suggestion
    rateFeedConfig.rateFeedID = Config.rateFeedID("relayed:PHPUSD");
```

2024-08-20 12:21 UTC, philbow61 commented on script/upgrades/PUSO/Config.sol
> +      referenceRateFeedID: Config.rateFeedID("PHPUSD"),
```suggestion
      referenceRateFeedID: Config.rateFeedID("relayed:PHPUSD"),
```

2024-08-21 15:31 UTC, philbow61 requested changes
LGTM 👍 nice work 
please verify the contracts on mainnet and alfajores

2024-08-21 15:31 UTC, philbow61 commented on broadcast/PUSO-00-Create-Proxies.sol/62320/run-latest.json
With the rateFeed alias not being on Baklava we won't deploy PUSO to Baklava so I think you can remove this one

2024-08-22 12:44 UTC, philbow61 approved these changes

2024-08-26 09:17 UTC, bowd commented on script/upgrades/PUSO/Config.sol
> +    }
We can get rid of this

2024-08-26 09:24 UTC, bowd approved these changes

2024-08-26 09:24 UTC, bowd commented on script/upgrades/PUSO/Config.sol
> +    }
We can get rid of this

2024-08-26 09:24 UTC, bowd commented on script/upgrades/PUSO/PUSOChecks.swap.sol
> +  }
Does the `assertApproxEq` from forge-std/Test.sol not work here?

2024-08-26 09:54 UTC, merged