feat: add medianDeltaBreakear deployment script
mento-protocol/mento-deployment pull request #69
Opened 2023-06-16 11:58 UTC by nvtaveras

### Description

This adds the script for deploying the median delta breaker with default/empty configuration and transferring it to governance so that we can later re-configure it with the right parameters in the MU02 activation CGP.

### Other changes

-

### Tested

Ran the deployment simulation locally

### Related issues

- Fixes https://github.com/mento-protocol/mento-deployment/issues/64

### Backwards compatibility

Yes, since the old constructor didn't change

### Documentation

-

2023-06-16 12:45 UTC, ninocomputer approved these changes

2023-06-16 17:08 UTC, bayological requested changes

2023-06-16 17:08 UTC, bayological commented on script/upgrades/MU02/MU02-01-Deploy-MedianDeltaBreaker.sol
The deployment script is fine, however the location and file name are not in line with the convention. The folder under upgrades is intended to collect all deployment scripts related to a particular upgrade. We only have one upgrade, MU01, and this folder should contain everything related to MC Mento developments.

The location of this script should be ``` upgrades/MU01/deploy ``` and the name should be ``` MU01-05-Deploy-MedianDeltaBreaker.sol ``` (Number should be the next one up from max)

2023-06-21 09:24 UTC, nvtaveras commented on script/upgrades/MU02/MU02-01-Deploy-MedianDeltaBreaker.sol
Chatted with Bayo offline about this, decided that we will stick to MU01 for all the new deployment scripts. I have also moved the breakerBox deployment script to the MU01 folder (https://github.com/mento-protocol/mento-deployment/pull/68)

2023-06-21 17:48 UTC, bayological approved these changes

2023-06-22 08:23 UTC, merged